### ISSUE TITLE
有沒有RTMP支持阿

### ISSUE THREAD

**Issue by herman602** [depthlove/FFmpeg-X264-Encode-for-iOS#1]
請問這個編譯好的FFMPEG有沒有支持RTMP啊?
沒有的話要怎麼加入呢
謝謝!

**Comment by depthlove** [comment]
我只是将x264编译进了ffmpeg，对于rtmp以及openssl我没有编译进去，如何编译，这个比较简单，我没有写步骤，你到网上搜搜吧

**Comment by herman602** [comment]
了解了, 謝謝!
