### ISSUE TITLE
你好，xcode 运行后，当我点击停止录制按钮，就崩溃了

### ISSUE THREAD

**Issue by hongtianpei1990gmail** [depthlove/FFmpeg-X264-Encode-for-iOS#2]
![image](https://cloud.githubusercontent.com/assets/17697229/19955265/a48278a8-a1ba-11e6-9cd5-97444752a031.png)

这个是崩溃的截图，我的ios 系统是9.3.2系统，这个 bug 是每次都崩溃的

**Comment by depthlove** [comment]
这个需要调整逻辑，当点击停止按钮了，此时 x264 对象会被释放，但是 x264 编码的逻辑还在执行，因为 x264 相关对象的内存被释放了，所以会出现奔溃，即，图中崩溃处 address=0x0

这个问题，当我有空闲时间，我会改下。

**Comment by hongtianpei1990gmail** [comment]
感谢你的回复，能指导下修改哪一行的代码嘛？最近项目需要涉及到视频这块，比较急

**Comment by pwjpj52** [comment]
请问为什么录制的视频使用VLC播放的特别快

**Comment by depthlove** [comment]
You can see v3.0.0, https://github.com/depthlove/FFmpeg-X264-Encode-for-iOS/releases
