### ISSUE TITLE
 请问为什么录制的视频使用VLC播放的特别快

### ISSUE THREAD

**Issue by pwjpj52** [depthlove/FFmpeg-X264-Encode-for-iOS#3]
如题，除了崩溃问题外，录的视频使用VLC播放特别快，请问如何解决

**Comment by depthlove** [comment]
H.264 file has no speed controller info, so YUV will be render very quickly. You can Package H.264 streaming into .mp4 container that the player can play it normally.

You can see v3.0.0, https://github.com/depthlove/FFmpeg-X264-Encode-for-iOS/releases
